version: 2

build:
    image: latest
    jobs:
        post_build:
            - SPHINX_APIDOC_OPTIONS=["members", "show-inheritance", "inherited-members"]

python:
    version: "3.8"
    install:
        - requirements: requirements/requirements_docs.txt
        - method: setuptools
          path: .
    system_packages: true

sphinx:
    configuration: docs/conf.py
