[tool.isort]
profile = "black"

[build-system]
requires = [
  "pip>=19.1.1",
  "setuptools>=28",
  "setuptools_scm>=3.2.0",
  "wheel",
]

[tool.black]
line-length = 79

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(message)s"