name: Build and test fmu-sumo

on:
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v3
      - name: Azure Login
        uses: Azure/login@v1
        with:
          client-id: f96c150d-cacf-4257-9cc9-54b2c68ec4ce
          tenant-id: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
          subscription-id: 87897772-fb27-495f-ae40-486a2df57baa
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies and . 
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install . 
      - name: Check some stuff
        run: |
          pip check
          pip show fmu-sumo
          pip show openvds
          python --version
          pip --version
          pytest --version
          python -c "import sys; print(sys.version)"
          python -c "from fmu.sumo.explorer import Explorer; sumo = Explorer('dev', interactive=False)"
          python -c "import sys; print(sys.version)"
      - name: Test with pytest
        run: |
          access_token=$(az account get-access-token --scope api://88d2b022-3539-4dda-9e66-853801334a86/.default --query accessToken --output tsv)
          export ACCESS_TOKEN=$access_token
          pytest -s tests/dummy_test.py 
